# Generated by Django 6.0.8 on 2026-08-07 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_rename_store_prod_is_avail_idx_store_produ_is_avai_44f824_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamescore',
            name='promo_code_issued',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='game_scores', to='store.promocode'),
        ),
    ]
