services:
  - type: web
    name: foxtech
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn foxtech.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.0
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: foxtech.onrender.com
