# Generated by Django 6.0.8 on 2026-08-07 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_update'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, unique=True)),
                ('source', models.CharField(default='game', max_length=50)),
                ('score', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promo_codes', to='accounts.userprofile')),
            ],
            options={
                'verbose_name': 'promo code',
                'verbose_name_plural': 'promo codes',
                'ordering': ('-created_at',),
            },
        ),
    ]
